export class CharacterClass {
  className: ClassNames;
  classImagePath: string;

  constructor(className: ClassNames) {
    this.className = className;
    this.classImagePath = classImages[className];
  }
}

enum ClassNames {
  adele = "Adele",
  angelicBuster = "Angelic Buster",
  aran = "Aran",
  ark = "Ark",
  battleMage = "Battle Mage",
  beastTamer = "Beast Tamer",
  bishop = "Bishop",
  blaster = "Blaster",
  blazeWizard = "Blaze Wizard",
  bowMaster = "Bow Master",
  buccaneer = "Buccaneer",
  cadena = "Cadena",
  cannoneer = "Cannoneer",
  corsair = "Corsair",
  darkKnight = "Dark Knight",
  dawnWarrior = "Dawn Warrior",
  demonAvenger = "Demon Avenger",
  demonSlayer = "Demon Slayer",
  dualBlade = "Dual Blade",
  evan = "Evan",
  hayato = "Hayato",
  hero = "Hero",
  hoyoung = "Hoyoung",
  illium = "Illium",
  jett = "Jett",
  kain = "Kain",
  kaiser = "Kaiser",
  kanna = "Kanna",
  kinesis = "Kinesis",
  lara = "Lara",
  luminous = "Luminous",
  firePoisonMage = "Fire/Poison Mage",
  iceLightningMage = "Ice/Lightning Mage",
  marksman = "Marksman",
  mechanic = "Mechanic",
  mercedes = "Mercedes",
  mihile = "Mihile",
  nightLord = "Night Lord",
  nightWalker = "Night Walker",
  paladin = "Paladin",
  pathfinder = "Pathfinder",
  phantom = "Phantom",
  shade = "Shade",
  shadower = "Shadower",
  thunderBreaker = "Thunder Breaker",
  wildHunter = "Wild Hunter",
  windArcher = "Wind Archer",
  xenon = "Xenon",
  zero = "Zero",
}

const classImages: Record<ClassNames, string> = {
  [ClassNames.adele]: "./images/classes/adele.png",
  [ClassNames.angelicBuster]: "./images/classes/angelicBuster.png",
  [ClassNames.aran]: "./images/classes/aran.png",
  [ClassNames.ark]: "./images/classes/ark.png",
  [ClassNames.battleMage]: "./images/classes/battleMage.png",
  [ClassNames.beastTamer]: "./images/classes/beastTamer.png",
  [ClassNames.bishop]: "./images/classes/bishop.png",
  [ClassNames.blaster]: "./images/classes/blaster.png",
  [ClassNames.blazeWizard]: "./images/classes/blazeWizard.png",
  [ClassNames.bowMaster]: "./images/classes/bowMaster.png",
  [ClassNames.buccaneer]: "./images/classes/buccaneer.png",
  [ClassNames.cadena]: "./images/classes/cadena.png",
  [ClassNames.cannoneer]: "./images/classes/cannoneer.png",
  [ClassNames.corsair]: "./images/classes/corsair.png",
  [ClassNames.darkKnight]: "./images/classes/darkKnight.png",
  [ClassNames.dawnWarrior]: "./images/classes/dawnWarrior.png",
  [ClassNames.demonAvenger]: "./images/classes/demonAvenger.png",
  [ClassNames.demonSlayer]: "./images/classes/demonSlayer.png",
  [ClassNames.dualBlade]: "./images/classes/dualBlade.png",
  [ClassNames.evan]: "./images/classes/evan.png",
  [ClassNames.hayato]: "./images/classes/hayato.png",
  [ClassNames.hero]: "./images/classes/hero.png",
  [ClassNames.hoyoung]: "./images/classes/hoyoung.png",
  [ClassNames.illium]: "./images/classes/illium.png",
  [ClassNames.jett]: "./images/classes/jett.png",
  [ClassNames.kain]: "./images/classes/kain.png",
  [ClassNames.kaiser]: "./images/classes/kaiser.png",
  [ClassNames.kanna]: "./images/classes/kanna.png",
  [ClassNames.kinesis]: "./images/classes/kinesis.png",
  [ClassNames.lara]: "./images/classes/lara.png",
  [ClassNames.luminous]: "./images/classes/luminous.png",
  [ClassNames.firePoisonMage]: "./images/classes/firePoisonMage.png",
  [ClassNames.iceLightningMage]: "./images/classes/iceLightningMage.png",
  [ClassNames.marksman]: "./images/classes/marksman.png",
  [ClassNames.mechanic]: "./images/classes/mechanic.png",
  [ClassNames.mercedes]: "./images/classes/mercedes.png",
  [ClassNames.mihile]: "./images/classes/mihile.png",
  [ClassNames.nightLord]: "./images/classes/nightLord.png",
  [ClassNames.nightWalker]: "./images/classes/nightWalker.png",
  [ClassNames.paladin]: "./images/classes/paladin.png",
  [ClassNames.pathfinder]: "./images/classes/pathfinder.png",
  [ClassNames.phantom]: "./images/classes/phantom.png",
  [ClassNames.shade]: "./images/classes/shade.png",
  [ClassNames.shadower]: "./images/classes/shadower.png",
  [ClassNames.thunderBreaker]: "./images/classes/thunderBreaker.png",
  [ClassNames.wildHunter]: "./images/classes/wildHunter.png",
  [ClassNames.windArcher]: "./images/classes/windArcher.png",
  [ClassNames.xenon]: "./images/classes/xenon.png",
  [ClassNames.zero]: "./images/classes/zero.png",
};
